# Generated by Django 4.2.11 on 2024-08-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_rename_expense_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(help_text="Enter date in YYYY-MM-DD format"),
        ),
    ]
