# Generated by Django 4.2.11 on 2024-08-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0006_transaction_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("home_expenditure", "Home Expenditure"),
                    ("personal_expense", "Personal Expense"),
                    ("bills", "Bills"),
                    ("others", "Others"),
                ],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
